### ISSUE TITLE
Cannot read property of undefined in grabber.. grabber.js 42

### ISSUE THREAD

**Issue by gateway** [gochain-io/explorer#35]
I'm testing this explorer and have everything set up.. I had it running then had to make some changes and restart, it started to grab all the missing blocks but eventually stopped with an error.. I haven't had time to debug it but thought I would let the dev know.

```
DB successfully written block number 49077  block hash :0x504a79924037153d0dd94a02010cf8b4e5fbd613896329f46c6b915b929cb1be
[0] Skip: Duplicate key 49227: WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: blockDB.blocks index: number_1 dup key: { : 49227 }","op":{"difficulty":"5","extraData":"0x322e312e31362f6c696e75782d616d6436342f676f312e31302e320000000000","gasLimit":210284448,"gasUsed":1029000,"hash":"0xdb4e5fb111f01f0eb4ef5f3211dd63f58eca5d40a5bc314ef926b832c4ae9274","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x6e2cad5118b75420f7d73cfbd6db072523de8366","nonce":"0x0000000000000000","number":49227,"parentHash":"0x0bfbe7a31d7b2bf35a8f39a8c7e5639292d83f73c59a76070950918f980e26fe","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":5909,"stateRoot":"0xd3cdf053677eca3715c5a92ad17c56f1100ab860e3cb74efcb87434310cb76b1","timestamp":1527364110,"totalDifficulty":"186967","transactionsRoot":"0xc991dfdaf989970e2b119e8d51e85004b7f15b4f30c3b6f84eb8fa074c023d29","transactionsCount":49,"_id":"5b09ba2356623d0836c50523","uncles":[],"__v":0}})
[0] Transactions and block has been removed calling grab again: 49227
[0] Transactions and block has been removed calling grab again: 49229
[0] Transactions and block has been removed calling grab again: 49229
[0] hash  0x0a976cbc8707dc44870b02bb897df8f7b1ed863fef42a9ef71c1d0ccfbee399e  converted into block: 49230
[0] hash  0x5c98c0de547e8f0f760a0ae60476dc79e8b59e63f3268d73ff201ea324023f0c  converted into block: 49231
[0] Block:  49076  trying to add transactions to db: 452  block hash :0x842f36564d04b0b85118cc7f561f79d99e414d233210e1e2b7b49a79532a8b68 Miner: 0x10a8a552c8a8945f32f6fded5e44d9101b3491d8
[0] DB successfully written block number 49076  block hash :0x842f36564d04b0b85118cc7f561f79d99e414d233210e1e2b7b49a79532a8b68
[0] Got new hash: 0xa27e73adf71ef7af60d3fd480747e1e3dd5a9e154c318f9746e7793bc25bf66e
[0] Got new hash: 0x32aeacc94fe00dffe5843bbf5325051921f84ebf9a07a782605d892bbe70560d
[0] Got new hash: 0x929bc39d6f96a6c96a2724209091669808be71d405f03e9a10444daa08f53fbf
[0] hash  0x32aeacc94fe00dffe5843bbf5325051921f84ebf9a07a782605d892bbe70560d  converted into block: 49232
[0] Block:  49227  trying to add transactions to db: 49  block hash :0xdb4e5fb111f01f0eb4ef5f3211dd63f58eca5d40a5bc314ef926b832c4ae9274 Miner: 0x6e2cad5118b75420f7d73cfbd6db072523de8366
[0] /var/www/gochain/tools/grabber.js:42
[0]                 console.log("hash ", hash, " converted into block:", block.number);
[0]                                                                            ^
[0] 
[0] TypeError: Cannot read property 'number' of undefined
[0]     at Object.callback (/var/www/gochain/tools/grabber.js:42:76)
[0]     at /var/www/gochain/node_modules/web3/lib/web3/method.js:142:25
[0]     at /var/www/gochain/node_modules/web3/lib/web3/requestmanager.js:86:20
[0]     at XMLHttpRequest.request.onreadystatechange (/var/www/gochain/node_modules/web3/lib/web3/httpprovider.js:118:13)
[0]     at XMLHttpRequestEventTarget.dispatchEvent (/var/www/gochain/node_modules/xhr2/lib/xhr2.js:64:18)
[0]     at XMLHttpRequest._setReadyState (/var/www/gochain/node_modules/xhr2/lib/xhr2.js:354:12)
[0]     at XMLHttpRequest._onHttpResponseEnd (/var/www/gochain/node_modules/xhr2/lib/xhr2.js:509:12)
[0]     at IncomingMessage.<anonymous> (/var/www/gochain/node_modules/xhr2/lib/xhr2.js:469:24)
[0]     at emitNone (events.js:111:20)
[0]     at IncomingMessage.emit (events.js:208:7)
[0]     at endReadableNT (_stream_readable.js:1064:12)
[0]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0] node tools/grabber.js  exited with code 1

```
The site is still running and im able to see data, just not getting any more blocks.

The refresh icon just stalls.. I see the POST command for /stats

Cheers!

**Comment by gateway** [comment]
enabled debug on mongo looks like im hitting a request limit in requestmanager.js:239

```
[0] Mongoose: blocks.insert({ difficulty: '5', extraData: '0x322e312e31362f6c696e75782d616d6436342f676f312e31302e320000000000', gasLimit: 210284448, gasUsed: 7707000, hash: '0x0256e4662d7f832eb68d55ac2493505ffd13431cb98a692b21811cef34664125', logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', miner: '0xdd7e460302a911f9162a208370cdcdc37b892453', nonce: '0x0000000000000000', number: 49470, parentHash: '0x5ec35a4f3134f130f49ec2921c0644cd940ca28334ae958a08aa0f51ee6b64db', sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347', size: 40249, stateRoot: '0xac2445d16ad931da02bbfca8c09875af2c74b2b715b51cb7fd78373d92af4610', timestamp: 1527365325, totalDifficulty: '188182', transactionsRoot: '0x3d503279331936e1a78e07b04f4806d52407465800e93a4b727904df61a61c37', transactionsCount: 367, _id: ObjectId("5b09c4036039381653bba755"), uncles: [], __v: 0 })
[0] DB successfully written block number 49470  block hash :0x0256e4662d7f832eb68d55ac2493505ffd13431cb98a692b21811cef34664125
[0] Got new hash: 0x0b79bfc5384ee7d3030c0a494b808fa0106a59245c87c1d82b0f6e5b49501bba
[0] /var/www/gochain/node_modules/web3/lib/web3/requestmanager.js:239
[0]             throw errors.InvalidResponse(results);
[0]             ^
[0] 
[0] Error: You hit the request limit
[0]     at Object.InvalidResponse (/var/www/gochain/node_modules/web3/lib/web3/errors.js:38:16)
[0]     at /var/www/gochain/node_modules/web3/lib/web3/requestmanager.js:239:26
[0]     at XMLHttpRequest.request.onreadystatechange (/var/www/gochain/node_modules/web3/lib/web3/httpprovider.js:118:13)
[0]     at XMLHttpRequestEventTarget.dispatchEvent (/var/www/gochain/node_modules/xhr2/lib/xhr2.js:64:18)
[0]     at XMLHttpRequest._setReadyState (/var/www/gochain/node_modules/xhr2/lib/xhr2.js:354:12)
[0]     at XMLHttpRequest._onHttpResponseEnd (/var/www/gochain/node_modules/xhr2/lib/xhr2.js:509:12)
[0]     at IncomingMessage.<anonymous> (/var/www/gochain/node_modules/xhr2/lib/xhr2.js:469:24)
[0]     at emitNone (events.js:111:20)
[0]     at IncomingMessage.emit (events.js:208:7)
[0]     at endReadableNT (_stream_readable.js:1064:12)
[0]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0] node tools/grabber.js  exited with code 1
[1] GET /xmlrpc.php 200 70.296 ms - 11309
[1] GET / 200 11.616 ms - 11309

```
